version: '3.8'

services:
  yii2-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
      # Исключаем vendor, чтобы не перезаписался
      - /var/www/html/vendor
      - /var/www/html/web/assets

    container_name: yii2-api4
